### PR TITLE
Drag and drop cells from a notebook

### PR DESCRIPTION
**Pull request by hbcarlos**
The first prototype of drag and drop from a notebook.
We need to improve:

- [ ] Check that the cell comes from the same notebook model.

- [ ] Interpolate the dropped position in pixels to the position in cells at the gridstack instance.

Screen Recording 2020-10-08 at 14 25 18

### CODE REVIEW

**Comment by hbcarlos** [comment]
Thanks for updating to rc5!
I'm gonna work on this branch to try to solve these issues:

- [ ] Check that the cell comes from the same notebook model.
- [ ] Interpolate the dropped position in pixels to the position in cells at the gridstack instance.

**Comment by jtpio** [comment]
> Interpolate the dropped position in pixels to the position in cells at the gridstack instance.

Sounds like this could be done in a separate PR?

**Comment by hbcarlos** [comment]
yep, I'll do that one in another PR

**Comment by jtpio** [comment]
Nice, thanks!

Then let's merge and iterate in follow-up PRs.

**Pull request merged**
