### PR TITLE
New voila and voila editor buttons

### PR DESCRIPTION
**Pull request by hbcarlos**
Added two buttons in the Notebook toolbar to open the notebook in Voila and in Voila Editor.
Screenshot 2020-10-29 at 13 56 20

Added a button in the Voila Editor toolbar to open the notebook in Voila.
Screenshot 2020-10-29 at 13 56 27

### CODE REVIEW

**Comment by hbcarlos** [comment]
We should change the Voila Editor icon to a Voila icon with a pen inside or something like that.

**Comment by jtpio** [comment]
Nice, thanks!

**Comment by jtpio** [comment]
> We should change the Voila Editor icon to a Voila icon with a pen inside or something like that.

Yes we can iterate on the icons in follow-up PRs.

**Comment by jtpio** [comment]
And maybe be able to reuse the icons from `@jupyter-voila/jupyterlab-preview` if we decide to expose them from there.

**Comment by jtpio** [comment]
Working nicely on Binder!

binder-voila

**Pull request merged**
